const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {simulate,R,plain}=require('./full-simulation.cjs');
const root=path.resolve(__dirname,'..'),out=path.join(root,'test-output'),current=JSON.parse(fs.readFileSync(path.join(root,'current-build.json'))),limit=JSON.parse(fs.readFileSync(path.join(root,'release.json'))).last_round;
const start=Number(process.env.START_ROUND||6),results={identifier:current.identifier,start,limit,checks:[],errors:[],failedRequests:[]};
let runningBrowser;
const pass=t=>{results.checks.push(t);console.log('PASS '+t);};
(async()=>{
 const {rounds}=await simulate(),browser=runningBrowser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']}),context=await browser.newContext({viewport:{width:1600,height:1000},acceptDownloads:true});
 await context.addInitScript(()=>localStorage.setItem('nch-urban-game-v1','untouched 2D sentinel'));
 const page=await context.newPage();page.on('pageerror',e=>results.errors.push(e.message));page.on('requestfailed',r=>results.failedRequests.push({url:r.url(),error:r.failure()?.errorText}));await page.goto((process.env.URBAN_REVIEW_URL||'http://127.0.0.1:8770/'),{waitUntil:'networkidle'});await page.waitForFunction(()=>!!globalThis.__URBAN_REVIEW__);
 for(const [name,digest]of Object.entries(current.payload_sha256)){const response=await context.request.get((process.env.URBAN_REVIEW_URL||'http://127.0.0.1:8770/')+name);assert.equal(response.status(),200,name);assert.equal(require('node:crypto').createHash('sha256').update(await response.body()).digest('hex'),digest,name);}pass('Every served payload matches its build checksum');
 const read=()=>page.evaluate(()=>__URBAN_REVIEW__.read());
 const panel=async(name,open)=>{if((await page.locator('#'+name+'Toggle').getAttribute('aria-expanded')==='true')!==open)await page.locator('#'+name+'Toggle').click();};
 const click=async(x,y)=>{const p=await page.evaluate(([x,y])=>__URBAN_REVIEW__.cellToScreen(x,y),[x,y]);assert(p.x>0&&p.x<1600&&p.y>110&&p.y<900,JSON.stringify(p));await page.mouse.click(p.x,p.y);};
 const checkpoint=async(name)=>{const expected=await read();await page.locator('#saveButton').click();const pending=page.waitForEvent('download');await page.locator('#downloadReview').click();const save=path.join(out,name+'.json');await(await pending).saveAs(save);assert.deepEqual(JSON.parse(fs.readFileSync(save)),expected);await page.locator('#closeModal').click();await page.reload({waitUntil:'networkidle'});await page.waitForFunction(()=>!!globalThis.__URBAN_REVIEW__);assert.deepEqual(await read(),expected);await page.locator('#saveFile').setInputFiles(save);await page.locator('#confirmOpen').click();assert.deepEqual(await read(),expected);};
 const initial=start===6?JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures/build-011/round-5-complete.json'))):{...rounds[start-1].before,reviewLimit:limit,reviewComplete:false};
 await page.locator('#saveFile').setInputFiles({name:'qa-boundary.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(initial))});await page.locator('#confirmOpen').click();if(start===6){assert.equal((await read()).state.round,5);assert.equal((await read()).reviewComplete,false);await page.locator('#nextButton').click();assert.equal((await read()).state.round,6);pass('Build011 complete save retains its village and continues normally to Round6');}
 const decks=JSON.parse(fs.readFileSync(path.join(root,'src/recovered/sources.json'))),{roundSource}=await import('../src/source-content.js');
 for(let n=start;n<=limit;n++){
  await panel('journal',true);await panel('tools',true);assert.equal((await read()).state.round,n);await page.locator('#sourceTab').click();for(let d=0;d<(n<=10?2:1);d++){await page.locator('#sourceDeck').selectOption(String(d));const expected=roundSource(decks,n,d);assert.equal(await page.locator('#storyText').textContent(),expected.text);assert.equal(await page.locator('#sourceImages img').count(),expected.images.length);await page.locator('#sourceImages img').evaluateAll(async imgs=>{for(const img of imgs)img.loading='eager';await Promise.all(imgs.map(img=>img.decode()));});}if(n>10)assert(await page.locator('#sourceDeck option[value="1"]').evaluate(option=>option.disabled));await page.locator('#sourceDeck').selectOption('0');await page.locator('#taskTab').click();await page.locator('#nextButton').click();assert.equal((await read()).state.round,n);assert.equal((await read()).reviewComplete,false);
  await page.locator('#overheadButton').click();await page.locator('#fitButton').click();await panel('journal',false);await panel('tools',false);let selected=null;
  for(const action of rounds[n-1].actions){if(action.check){await panel('journal',true);await page.locator('#checklist input').check();await panel('journal',false);continue;}if(action.tool!==selected){await panel('tools',true);await page.locator(`[data-tool="${action.tool}"]`).click();await panel('tools',false);selected=action.tool;}await click(action.x,action.y);}
  if(n>=11){const village=(await read()).state,visuals=await page.evaluate(()=>__URBAN_REVIEW__.visuals());assert.equal(visuals.filter(v=>v.smokeBounds).length,village.structures.filter(b=>b.type==='factory').length);assert(visuals.filter(v=>v.smokeBounds).every(v=>v.smokeBounds.size===4));if(n>=12)assert.equal(visuals.filter(v=>v.bridgeMaterial==='iron').length,Object.values(village.terrain.bridge).filter(b=>b.material==='iron').length);if(n>=14){assert.equal(visuals.filter(v=>v.railway===1).length,Object.keys(village.terrain.rail1).length);assert(visuals.some(v=>v.railBridge));}if(n>=17)assert.equal(visuals.filter(v=>v.railway===2).length,Object.keys(village.terrain.rail2).length);}
  assert.deepEqual(plain(R.counts((await read()).state)),rounds[n-1].counts);assert.deepEqual(plain(R.tasks((await read()).state).filter(t=>!t.done)),[]);assert.equal((await read()).state.teacherOverrides.length,0);await panel('journal',true);await page.locator('#nextButton').click();assert.equal((await read()).state.round,n===limit?n:n+1);assert.equal((await read()).reviewComplete,n===limit);if(n===limit)await page.locator('#exploreComplete').click();await checkpoint('full-round-'+n);pass(`Round${n}: exact source, normal UI actions, checklist gate, advancement, save/reload/reopen`);
 }
 if(limit===20){
  const complete=await read();assert(complete.state.finished);assert.equal(complete.state.snapshots.length,21);assert.equal(complete.state.structures.length,196);await panel('journal',true);await page.locator('#nextButton').click();assert.equal(await page.locator('#closingText').textContent(),decks[0].slides.find(s=>s.number===34).text);const {reflectionQuestions}=await import('../src/source-content.js');for(let i=0;i<3;i++){assert.equal(await page.locator('#reflectionFields label').nth(i).locator('span').textContent(),`${i+1}. ${reflectionQuestions.board[i]}`);await page.locator('#reflection-'+i).fill('QA reflection '+(i+1)+' — preserved after reopening.');}await page.locator('#questionSet').selectOption('slides');for(let i=0;i<3;i++){assert.equal(await page.locator('#reflectionFields label').nth(i).locator('span').textContent(),`${i+1}. ${reflectionQuestions.slides[i]}`);assert.equal(await page.locator('#reflection-'+i).inputValue(),'QA reflection '+(i+1)+' — preserved after reopening.');}
  const pending=page.waitForEvent('download');await page.locator('#downloadReflections').click();const file=path.join(out,'final-reflections.txt');await(await pending).saveAs(file);const text=fs.readFileSync(file,'utf8');for(const q of reflectionQuestions.slides)assert(text.includes(q));for(let i=1;i<=3;i++)assert(text.includes('QA reflection '+i));await page.screenshot({path:path.join(out,'final-reflections.png')});await page.locator('#exploreComplete').click();await checkpoint('round-20-with-reflections');assert.equal((await read()).state.questionSet,'slides');assert.equal((await read()).state.answers.length,3);assert((await read()).state.answers.every(a=>a.includes('preserved')));await page.locator('#nextButton').click();assert.equal((await read()).state.snapshots.length,21);await page.locator('#exploreComplete').click();pass('Final original conclusion, both question sets, answer persistence, text export, and single completion snapshot');
 }
 await page.locator('#isometricButton').click();await page.locator('#fitButton').click();await page.screenshot({path:path.join(out,'full-round-'+limit+'.png')});assert.equal(await page.evaluate(()=>localStorage.getItem('nch-urban-game-v1')),'untouched 2D sentinel');assert.deepEqual(results.errors,[]);results.abortedRequests=results.failedRequests.filter(r=>r.error==='net::ERR_ABORTED');assert.deepEqual(results.failedRequests.filter(r=>r.error!=='net::ERR_ABORTED'),[]);pass('No script or asset failures; navigation-cancelled requests recorded separately; accepted 2D storage remains untouched');
 results.status='passed';fs.writeFileSync(path.join(out,`full-browser-${start}-${limit}.json`),JSON.stringify(results,null,2));await browser.close();
})().catch(async e=>{await runningBrowser?.close();results.status='failed';results.failure=e.stack;fs.writeFileSync(path.join(out,`full-browser-${start}-${limit}.json`),JSON.stringify(results,null,2));console.error(e);process.exit(1);});
