const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {simulate,R}=require('./full-simulation.cjs'),root=path.resolve(__dirname,'..'),out=path.join(root,'test-output');
const report={identifier:JSON.parse(fs.readFileSync(path.join(root,'current-build.json'))).identifier,checks:[],errors:[]},pass=t=>{report.checks.push(t);console.log('PASS '+t);};
(async()=>{const {rounds}=await simulate(),browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});try{
 const page=await browser.newPage({viewport:{width:1600,height:1000},acceptDownloads:true});page.on('pageerror',e=>report.errors.push(e.message));await page.goto((process.env.URBAN_REVIEW_URL||'http://127.0.0.1:8770/'),{waitUntil:'networkidle'});await page.waitForFunction(()=>!!globalThis.__URBAN_REVIEW__);
 const read=()=>page.evaluate(()=>__URBAN_REVIEW__.read()),point=(x,y)=>page.evaluate(([x,y])=>__URBAN_REVIEW__.cellToScreen(x,y),[x,y]);
 const panel=async(name,open)=>{if((await page.locator('#'+name+'Toggle').getAttribute('aria-expanded')==='true')!==open)await page.locator('#'+name+'Toggle').click();};
 const select=async type=>{await panel('tools',true);await page.locator('[data-tool='+type+']').click();await panel('tools',false);};
 const load=async n=>{const v={...rounds[n-1].before,reviewLimit:20,reviewComplete:false};await page.locator('#saveFile').setInputFiles({name:'qa-round-'+n+'.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(v))});await page.locator('#confirmOpen').click();await page.locator('#overheadButton').click();await page.locator('#fitButton').click();await panel('journal',false);await panel('tools',false);};
 const click=async(x,y)=>{const p=await point(x,y);await page.mouse.click(p.x,p.y);};
 const idle=async()=>{const v=await page.evaluate(()=>__URBAN_REVIEW__.interaction());assert.equal(v.activePointer,null);assert.deepEqual(v.navigationPointers,[]);};
 await load(9);await select('demolish');let before=await read();await click(10,20);assert.deepEqual(await read(),before);const houses=before.state.structures.filter(b=>b.type==='house');await click(houses[0].x,houses[0].y);assert.equal((await read()).state.removed.length,1);await page.keyboard.press('Control+z');assert.deepEqual(await read(),before);await page.keyboard.press('Control+Shift+z');for(const b of houses.slice(1,5))await click(b.x,b.y);before=await read();await click(houses[5].x,houses[5].y);assert.deepEqual(await read(),before);assert.equal(before.state.removed.length,5);pass('Round9 demolition rejects nice houses, supports undo/redo, and stops at exactly five ordinary houses');
 await load(12);await select('iron');before=await read();await click(8,16);assert.equal((await read()).state.terrain.bridge['8,16'].material,'iron');await page.keyboard.press('Control+z');assert.deepEqual(await read(),before);await page.keyboard.press('Control+Shift+z');before=await read();await click(8,16);assert.deepEqual(await read(),before);pass('Round12 iron replacement supports undo/redo and repeated clicks preserve the crossing');
 await load(14);await select('rail1');let a=await point(2,31),b=await point(6,31);await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y,{steps:6});await page.keyboard.press('Escape');await page.mouse.up();await idle();assert.equal(Object.keys((await read()).state.terrain.rail1).length,5);await page.keyboard.press('Control+z');assert.equal(Object.keys((await read()).state.terrain.rail1).length,0);await page.keyboard.press('Control+Shift+z');a=await point(6,31);b=await point(9,31);await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y,{steps:5});const id=await page.evaluate(()=>__URBAN_REVIEW__.interaction().activePointer);await page.dispatchEvent('#villageCanvas','pointercancel',{pointerId:id,pointerType:'mouse'});await page.mouse.up();await idle();before=await read();assert.equal(Object.keys(before.state.terrain.rail1).length,8);assert(await page.evaluate(()=>__URBAN_REVIEW__.visuals().some(v=>v.railBridge)));await page.mouse.move(900,500);assert.deepEqual(await read(),before);await panel('journal',true);await page.locator('#nextButton').click();assert.equal((await read()).state.round,14);pass('Round14 rail dragging crosses water, groups undo, recovers from Escape/cancel, and blocks an incomplete network');
 await load(17);await select('rail2');before=await read();a=await point(0,31);b=await point(28,31);await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y,{steps:20});await page.mouse.up();await idle();let after=await read();assert.equal(Object.keys(after.state.terrain.rail2).length,29);assert.deepEqual(after.state.terrain.rail1,before.state.terrain.rail1);assert(R.tasks(after.state).find(t=>t.id==='eastWest').done);await page.locator('#saveButton').click();const pending=page.waitForEvent('download');await page.locator('#downloadReview').click();const save=path.join(out,'late-railway-save.json');await(await pending).saveAs(save);await page.locator('#closeModal').click();await page.reload({waitUntil:'networkidle'});await page.waitForFunction(()=>!!globalThis.__URBAN_REVIEW__);assert.deepEqual(await read(),after);await page.locator('#saveFile').setInputFiles(save);await page.locator('#confirmOpen').click();assert.deepEqual(await read(),after);pass('Round17 west-to-east dragging completes its separate layer and survives download/reload/reopen');
 assert.deepEqual(report.errors,[]);report.status='passed';
 }catch(e){report.status='failed';report.failure=e.stack;throw e;}finally{fs.writeFileSync(path.join(out,'late-actions-results.json'),JSON.stringify(report,null,2));await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
