const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {R}=require('./full-simulation.cjs'),root=path.resolve(__dirname,'..'),out=path.join(root,'test-output');
const report={identifier:JSON.parse(fs.readFileSync(path.join(root,'current-build.json'))).identifier,checks:[],errors:[],scenes:[]};
(async()=>{const {blankVillage}=await import('../src/review-state.js'),browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});try{
 const page=await browser.newPage({viewport:{width:1600,height:1000}});page.on('pageerror',e=>report.errors.push(e.message));await page.goto('http://127.0.0.1:8770/',{waitUntil:'networkidle'});await page.waitForFunction(()=>!!globalThis.__URBAN_REVIEW__);
 for(const [type,round]of [['house',20],['manor',20],['factory',4],['factory',20]]){
  const v=blankVillage();v.state.round=round;v.state.name='Model Study — QA';v.state.structures=[{id:1,type,size:R.TYPES[type].size,x:14,y:16,born:round}];v.state.nextId=2;v.roundStart=R.clone(v.state);await page.locator('#saveFile').setInputFiles({name:'generated-model-study.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(v))});await page.locator('#confirmOpen').click();for(const panel of ['journal','tools'])if(await page.locator('#'+panel+'Toggle').getAttribute('aria-expanded')==='false')await page.locator('#'+panel+'Toggle').click();await page.locator('[data-tool='+type+']').click();await page.locator('#focusBuilding').click();await page.locator('#zoomIn').click();await page.locator('#zoomIn').click();await page.locator('#inspectArt').scrollIntoViewIfNeeded();await page.waitForTimeout(200);await page.screenshot({path:path.join(out,`model-${type}-${round}.png`)});report.scenes.push({type,round,stats:await page.evaluate(()=>__URBAN_REVIEW__.rendererStats())});assert.equal((await page.evaluate(()=>__URBAN_REVIEW__.read())).state.structures[0].type,type);
  await page.mouse.move(770,600);await page.mouse.down({button:'middle'});await page.mouse.move(1050,600,{steps:8});await page.mouse.up({button:'middle'});await page.screenshot({path:path.join(out,`model-${type}-${round}-rotated.png`)});assert.equal((await page.evaluate(()=>__URBAN_REVIEW__.read())).state.structures.length,1);
 }
 await page.locator('#saveFile').setInputFiles(path.join(root,'test-output/round-20-with-reflections.json'));await page.locator('#confirmOpen').click();await page.locator('#fitButton').click();await page.screenshot({path:path.join(out,'crafted-full-town.png')});const before=await page.evaluate(()=>__URBAN_REVIEW__.read()),stats=await page.evaluate(()=>__URBAN_REVIEW__.rendererStats());report.scenes.push({type:'complete-city',stats});assert.equal(before.state.structures.length,196);for(let i=0;i<3;i++){await page.locator('#overheadButton').click();await page.locator('#isometricButton').click();await page.locator('#fitButton').click();}assert.deepEqual(await page.evaluate(()=>__URBAN_REVIEW__.read()),before);assert.deepEqual(report.errors,[]);report.checks.push('Four focused model views and rotations preserve source footprints and game state','Complete196-building village reopens and navigation preserves all data');report.status='passed';console.log(JSON.stringify(report,null,2));
 }catch(e){report.status='failed';report.failure=e.stack;throw e;}finally{fs.writeFileSync(path.join(out,'model-visuals-results.json'),JSON.stringify(report,null,2));await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
