const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto');
const source=fs.readFileSync(require('node:path').join(__dirname,'../src/recovered/rules.js'),'utf8');
const sandbox={module:{exports:{}}};vm.runInNewContext(source,sandbox);const R=sandbox.module.exports;globalThis.UrbanRules=R;
const api=import('../src/review-state.js');
const laterRounds=require('./fixtures/rounds-2-5.cjs');
const plain=value=>JSON.parse(JSON.stringify(value));
function finishRoundOne(v){for(let y=8;y<=12;y++)assert.equal(R.paint(v.state,'canal',7,y),null);assert.equal(R.place(v.state,'manor',10,20),null);v.state.checks['1-nearRiver']=true;}
async function throughRound(round){const {preparedVillage,advanceReview}=await api;const v=preparedVillage();finishRoundOne(v);assert.equal(advanceReview(v),null);for(let n=2;n<round;n++){for(const p of laterRounds[n].placements)assert.equal(R.place(v.state,...p),null);assert.equal(advanceReview(v),null);}return v;}
test('Rules remain exactly the recovered original script',()=>assert.equal(crypto.createHash('sha256').update(source).digest('hex'),'3ead711e66c2e84af5bfffa65365d8d850fc7070204da95d9aa0ef63576da0d9'));
test('Prepared village completes original setup without a teacher override',async()=>{const {preparedVillage}=await api;const v=preparedVillage();assert.equal(v.state.round,1);assert.equal(v.state.teacherOverrides.length,0);const setup=R.clone(v.state);setup.round=0;assert.equal(R.tasks(setup).filter(x=>!x.done).length,0);assert.equal(R.counts(v.state).house,10);assert.equal(v.state.snapshots.length,1);});
test('Round 1 retains its source requirements and advances normally to Round 2',async()=>{const {preparedVillage,advanceReview,validateReview}=await api;const v=preparedVillage();assert(advanceReview(v));assert.equal(R.paint(v.state,'canal',7,8),null);assert.equal(R.paint(v.state,'canal',7,9),null);assert.equal(R.place(v.state,'manor',10,20),null);assert(advanceReview(v));v.state.checks['1-nearRiver']=true;assert.equal(advanceReview(v),null);assert.equal(v.state.round,2);assert.equal(validateReview(v).reviewComplete,false);assert(advanceReview(v));});
test('Footprints, protected commons, disconnected canals, and duplicate houses remain enforced',async()=>{const {preparedVillage,advanceReview}=await api;const v=preparedVillage();assert(R.place(v.state,'manor',18,2));assert(R.place(v.state,'manor',28,31));assert.equal(R.place(v.state,'manor',10,20),null);assert(R.place(v.state,'manor',20,20));assert.equal(R.paint(v.state,'canal',7,8),null);assert.equal(R.paint(v.state,'canal',2,2),null);v.state.checks['1-nearRiver']=true;assert(advanceReview(v));});
test('Review imports enforce the current scope and valid completion flags',async()=>{const {preparedVillage,validateReview,LAST_ROUND}=await api;const v=preparedVillage();v.reviewLimit=LAST_ROUND+1;assert.throws(()=>validateReview(v),/range/);v.reviewLimit=LAST_ROUND;v.state.round=LAST_ROUND;v.roundStart.round=LAST_ROUND;v.reviewComplete=true;assert.throws(()=>validateReview(v),/unfinished/);v.reviewComplete='false';assert.throws(()=>validateReview(v),/flag/);});
test('All 3D placeholders, including the water-powered factory, fit their original footprints',async()=>{const {buildingModel}=await import('../src/models.js');const {Box3}=await import('three');for(const type of ['house','church','cemetery','store','pub','mine','park','manor','factory','trees']){const bounds=new Box3().setFromObject(buildingModel(type),true),half=R.TYPES[type].size/2;assert(bounds.min.x>=-half-.001&&bounds.max.x<=half+.001&&bounds.min.z>=-half-.001&&bounds.max.z<=half+.001,type+' exceeds its footprint');}});
test('Normal source progression completes Round 5 with 40 houses and continues without an override',async()=>{const {advanceReview,validateReview}=await api;const v=await throughRound(2);for(let n=2;n<=5;n++){assert(advanceReview(v));for(const p of laterRounds[n].placements)assert.equal(R.place(v.state,...p),null);assert.equal(R.counts(v.state).house,laterRounds[n].houses);assert(R.place(v.state,'house',0,30));assert.equal(advanceReview(v),null);assert.deepEqual(plain(validateReview(v).state),plain(v.state));}assert.equal(v.state.round,6);assert.equal(v.reviewComplete,false);assert.equal(v.state.finished,false);assert.equal(v.state.teacherOverrides.length,0);assert.deepEqual(plain(R.counts(v.state)),{house:40,church:2,cemetery:1,store:2,pub:2,mine:1,park:1,manor:2,factory:1});assert(advanceReview(v));});
test('The commons open in Round 3 and its nice house must remain wholly inside later',async()=>{const {advanceReview}=await api;const v=await throughRound(2);assert(R.place(v.state,'house',18,2));for(const p of laterRounds[2].placements)assert.equal(R.place(v.state,...p),null);advanceReview(v);assert.equal(R.place(v.state,'house',18,2),null);assert(R.place(v.state,'manor',10,24));assert(R.place(v.state,'manor',27,10));assert.equal(R.place(v.state,'manor',24,4),null);const b=v.state.structures.at(-1);v.state.round=4;assert(R.place(v.state,'manor',10,24,b.id));});
test('Round 4 rejects canal-only or dry-land factories and accepts the river bank',async()=>{const v=await throughRound(4);assert(R.place(v.state,'factory',5,10));assert(R.place(v.state,'factory',12,22));assert.equal(R.place(v.state,'factory',9,3),null);assert(R.place(v.state,'factory',9,6));});
test('Round 5 roads and bridges are optional; a second crossing blocks completion until erased',async()=>{const {advanceReview}=await api;const v=await throughRound(5);for(const p of laterRounds[5].placements)assert.equal(R.place(v.state,...p),null);assert(R.tasks(v.state).every(t=>t.done));assert(R.paint(v.state,'bridge',10,24));assert.equal(R.paint(v.state,'bridge',8,24),null);assert.equal(R.paint(v.state,'bridge',8,26),null);assert(advanceReview(v));assert.equal(R.paint(v.state,'erase',8,26),null);assert.equal(advanceReview(v),null);assert.equal(v.state.round,6);assert.equal(v.reviewComplete,false);});
test('Build 006 and 008 saves migrate losslessly, retain Round 1, and can continue',async()=>{const {validateReview,advanceReview,STORAGE,LEGACY_STORAGE}=await api;assert.notEqual(STORAGE,LEGACY_STORAGE);for(const id of ['006','008']){const legacy=JSON.parse(fs.readFileSync(require('node:path').join(__dirname,'fixtures/build-'+id+'-round-1-review.json'),'utf8'));const original=JSON.stringify(legacy);const v=validateReview(legacy);assert.equal(JSON.stringify(legacy),original);assert.equal(v.version,3);assert.equal(v.state.round,1);assert.equal(v.reviewComplete,false);assert.deepEqual(plain(v.state),plain(R.validateImport(legacy.state)));assert.deepEqual(plain(v.roundStart),plain(R.validateImport(legacy.roundStart)));assert.equal(advanceReview(v),null);assert.equal(v.state.round,2);}});
test('Earlier incomplete setup and Round 1 saves keep progress without being advanced',async()=>{const {validateReview,blankVillage,preparedVillage}=await api;for(const current of [blankVillage(),preparedVillage()]){const legacy={format:current.format,version:1,state:current.state,roundStart:current.roundStart,roundOneComplete:false};const v=validateReview(legacy);assert.equal(v.state.round,current.state.round);assert.deepEqual(plain(v.state),plain(current.state));assert.equal(v.reviewComplete,false);}});
